### ISSUE TITLE
Cursor is shifted in the symbol card lineplot [Firefox issue]

### ISSUE THREAD

**Issue by ztepler** [juster-finance/juster-app#15]
Вертикальная линия с выделяемым сегментом графика с ценой отображается левее позиции курсора мыши (смещена влево). На скриншоте красным крестом отображена примерная позиция курсора:
![image](https://user-images.githubusercontent.com/22714654/134210550-d71d8f5a-cf30-4117-acdd-9e6ee3cf263d.png)

Данная проблема воспроизводится в Firefox 91.0.2 (64-bit), в Chrome всё ок, однако подобное смещение также воспроизводится если курсор находится в самых нижних пикселях графика

**Comment by emilio** [comment]
Happens also in Safari. See https://github.com/webcompat/web-bugs/issues/94500#issuecomment-981623547 for diagnostic and a trivial fix.
